name: 'Terraform'

on:
  workflow_run:
    workflows: ["Deploy to ECR"]
    types:
      - completed
  
env:
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
  ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
  SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  REGION_NAME: ${{ secrets.REGION_NAME }}
  USER_AGENT: ${{ secrets.USER_AGENT }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  NUM_POSTS: ${{ secrets.NUM_POSTS }}
  SUBREDDIT_NAME: ${{ secrets.SUBREDDIT_NAME }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  HOST: ${{ secrets.HOST }}

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        
    - name: Check out code
      uses: actions/checkout@v3
    
    - name: Initialise and Apply
      run: |
        cd Terraform
        terraform init
        terraform plan -input=false -var "username=$USERNAME" -var "password=$PASSWORD" -var "database_name=$DATABASE_NAME" -var "access_key=$ACCESS_KEY" -var "secret_key=$SECRET_KEY" -var "region_name=$REGION_NAME" -var "user_agent=$USER_AGENT" -var "client_id=$CLIENT_ID" -var "client_secret=$CLIENT_SECRET" -var "num_posts=$NUM_POSTS" -var "subreddit_name=$SUBREDDIT_NAME" -var "bucket_name=$BUCKET_NAME" -var "host=$HOST"
        terraform destroy -auto-approve -target "aws_ecs_task_definition.sentiment-task" -var "username=$USERNAME" -var "password=$PASSWORD" -var "database_name=$DATABASE_NAME" -var "access_key=$ACCESS_KEY" -var "secret_key=$SECRET_KEY" -var "region_name=$REGION_NAME" -var "user_agent=$USER_AGENT" -var "client_id=$CLIENT_ID" -var "client_secret=$CLIENT_SECRET" -var "num_posts=$NUM_POSTS" -var "subreddit_name=$SUBREDDIT_NAME" -var "bucket_name=$BUCKET_NAME" -var "host=$HOST"
        terraform apply -auto-approve -var "username=$USERNAME" -var "password=$PASSWORD" -var "database_name=$DATABASE_NAME" -var "access_key=$ACCESS_KEY" -var "secret_key=$SECRET_KEY" -var "region_name=$REGION_NAME" -var "user_agent=$USER_AGENT" -var "client_id=$CLIENT_ID" -var "client_secret=$CLIENT_SECRET" -var "num_posts=$NUM_POSTS" -var "subreddit_name=$SUBREDDIT_NAME" -var "bucket_name=$BUCKET_NAME" -var "host=$HOST"
